title: "mascot-render-server"
description: "mascot-render-server"
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/cat2151/mascot-render-server
plugins:
  - jekyll-sitemap
