version = 1
layer_scroll_margin_ratio = 0.25
eye_blink_preferred_open_layer_names = [
    "目セット",
    "基本目",
    "普通目",
]
eye_blink_closed_layer_keywords = [
    "閉じ目",
    "目閉じ2",
    "目閉じ",
    "にっこり",
]
mouth_flap_open_layer_names = [
    "ほあー",
    "ほー",
    "おー",
    "お",
]
mouth_flap_closed_layer_names = [
    "むふ",
    "むん",
    "んむ",
    "ん",
    "んー",
]
